name: CI Pull Request Feature to Dev/Main

on:
  # Aciona a pipeline em pull requests aprovados para a branch dev
  pull_request_review:
    types: [submitted]
    branches:
      - dev

jobs:
  approved-pull-request:
    if: github.event.review.state == 'approved' && github.event.pull_request.head.ref != 'dev'
    runs-on: ubuntu-latest # Máquina virtual Ubuntu que executa o job

    steps:
      - run: echo "This Pull Request was Approved!"

      # Checkout do código do pull request
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do Node.js com uma versão específica
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14.x" # Versão do Node.js

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Executar o build da aplicação
      - name: Execute Build
        run: npm run build

      - name: Merge pull request
        if: success()
        run: echo "Merging pull request."

  #função que executa o merge do pull request apos approved-pull-request tiver exito
  automerge:
    name: Merge Pull Request
    runs-on: [ubuntu-latest]
    needs: [approved-pull-request]
    steps:
      - name: Merge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN_ACCESS }}
          script: |
            github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
