name: Pull Request Dev to Main

on:
  # Aciona a pipeline em pull requests aprovados para a branch dev
  pull_request_review:
    types: [submitted]
    branches:
      - main

jobs:
  approved-pull-request:
    if: github.event.review.state == 'approved' && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest # Máquina virtual Ubuntu que executa o job

    steps:
      - run: echo "This Pull Request was Approved!"

      # Checkout do código do pull request
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do Node.js com uma versão específica
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14.x" # Versão do Node.js

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Executar o build da aplicação
      - name: Execute Build
        run: npm run build

      # Executar os testes de integração
      - name: Run integration tests
        run: npm run test

      - name: Merge pull request
        if: success()
        run: echo "Merging pull request."

      - name: deploy
        run: |
          npm run build
          npx gh-pages -d dist


#função que executa o merge do pull request apos approved-pull-request tiver exito
  automerge:
    name: Merge Pull Request
    runs-on: [ubuntu-latest]
    needs: [approved-pull-request]
    steps:
      - name: Merge
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.TOKEN_ACCESS }}
          script: |
            github.pullRequests.merge ({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
